version: '3.9'

services:
  mongo:
    image: mongo:latest
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=rootpassword"
    ports:
      - 27017:27017 
    logging:
      driver: none
    volumes:
      - mongodb_data_container:/data/db
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - "DB_CONNECTION=mongodb://root:rootpassword@mongo:27017/?authSource=admin"
    volumes:
      - ./:/app
    depends_on:
      - mongo
    ports:
      - "80:80"
volumes:
  mongodb_data_container: